version: '3.9'

services:
  oss:
    image: opensearchproject/opensearch:2.15.0
    restart: always
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - opensearch-data1:/usr/share/opensearch/data 
volumes:
  opensearch-data1: